// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamecenter.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 要定義你Request & Res的Struct
type TestRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{0}
}
func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (dst *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(dst, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

type TestReply struct {
	State                string   `protobuf:"bytes,1,opt,name=State,json=state" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestReply) Reset()         { *m = TestReply{} }
func (m *TestReply) String() string { return proto.CompactTextString(m) }
func (*TestReply) ProtoMessage()    {}
func (*TestReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{1}
}
func (m *TestReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestReply.Unmarshal(m, b)
}
func (m *TestReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestReply.Marshal(b, m, deterministic)
}
func (dst *TestReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestReply.Merge(dst, src)
}
func (m *TestReply) XXX_Size() int {
	return xxx_messageInfo_TestReply.Size(m)
}
func (m *TestReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TestReply.DiscardUnknown(m)
}

var xxx_messageInfo_TestReply proto.InternalMessageInfo

func (m *TestReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type CreateGameRequest struct {
	GameType             string   `protobuf:"bytes,1,opt,name=GameType,json=gameType" json:"GameType,omitempty"`
	GameID               int32    `protobuf:"varint,2,opt,name=GameID,json=gameID" json:"GameID,omitempty"`
	Players              *Players `protobuf:"bytes,3,opt,name=Players,json=players" json:"Players,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameRequest) Reset()         { *m = CreateGameRequest{} }
func (m *CreateGameRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGameRequest) ProtoMessage()    {}
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{2}
}
func (m *CreateGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameRequest.Unmarshal(m, b)
}
func (m *CreateGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameRequest.Marshal(b, m, deterministic)
}
func (dst *CreateGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameRequest.Merge(dst, src)
}
func (m *CreateGameRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGameRequest.Size(m)
}
func (m *CreateGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameRequest proto.InternalMessageInfo

func (m *CreateGameRequest) GetGameType() string {
	if m != nil {
		return m.GameType
	}
	return ""
}

func (m *CreateGameRequest) GetGameID() int32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *CreateGameRequest) GetPlayers() *Players {
	if m != nil {
		return m.Players
	}
	return nil
}

type Players struct {
	PlayerList           []*Player `protobuf:"bytes,1,rep,name=PlayerList,json=playerList" json:"PlayerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Players) Reset()         { *m = Players{} }
func (m *Players) String() string { return proto.CompactTextString(m) }
func (*Players) ProtoMessage()    {}
func (*Players) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{3}
}
func (m *Players) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Players.Unmarshal(m, b)
}
func (m *Players) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Players.Marshal(b, m, deterministic)
}
func (dst *Players) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Players.Merge(dst, src)
}
func (m *Players) XXX_Size() int {
	return xxx_messageInfo_Players.Size(m)
}
func (m *Players) XXX_DiscardUnknown() {
	xxx_messageInfo_Players.DiscardUnknown(m)
}

var xxx_messageInfo_Players proto.InternalMessageInfo

func (m *Players) GetPlayerList() []*Player {
	if m != nil {
		return m.PlayerList
	}
	return nil
}

type Player struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	UUID                 string   `protobuf:"bytes,2,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,json=name" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{4}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Player) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateGameReply struct {
	State                string   `protobuf:"bytes,1,opt,name=State,json=state" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameReply) Reset()         { *m = CreateGameReply{} }
func (m *CreateGameReply) String() string { return proto.CompactTextString(m) }
func (*CreateGameReply) ProtoMessage()    {}
func (*CreateGameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{5}
}
func (m *CreateGameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameReply.Unmarshal(m, b)
}
func (m *CreateGameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameReply.Marshal(b, m, deterministic)
}
func (dst *CreateGameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameReply.Merge(dst, src)
}
func (m *CreateGameReply) XXX_Size() int {
	return xxx_messageInfo_CreateGameReply.Size(m)
}
func (m *CreateGameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameReply proto.InternalMessageInfo

func (m *CreateGameReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type GameInfoRequest struct {
	UserID               []int32  `protobuf:"varint,1,rep,packed,name=UserID,json=userID" json:"UserID,omitempty"`
	GameID               int32    `protobuf:"varint,2,opt,name=GameID,json=gameID" json:"GameID,omitempty"`
	GameType             string   `protobuf:"bytes,3,opt,name=GameType,json=gameType" json:"GameType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameInfoRequest) Reset()         { *m = GameInfoRequest{} }
func (m *GameInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GameInfoRequest) ProtoMessage()    {}
func (*GameInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{6}
}
func (m *GameInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInfoRequest.Unmarshal(m, b)
}
func (m *GameInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GameInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInfoRequest.Merge(dst, src)
}
func (m *GameInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GameInfoRequest.Size(m)
}
func (m *GameInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameInfoRequest proto.InternalMessageInfo

func (m *GameInfoRequest) GetUserID() []int32 {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *GameInfoRequest) GetGameID() int32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *GameInfoRequest) GetGameType() string {
	if m != nil {
		return m.GameType
	}
	return ""
}

type GameInfoReply struct {
	State                string   `protobuf:"bytes,1,opt,name=State,json=state" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameInfoReply) Reset()         { *m = GameInfoReply{} }
func (m *GameInfoReply) String() string { return proto.CompactTextString(m) }
func (*GameInfoReply) ProtoMessage()    {}
func (*GameInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{7}
}
func (m *GameInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInfoReply.Unmarshal(m, b)
}
func (m *GameInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInfoReply.Marshal(b, m, deterministic)
}
func (dst *GameInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInfoReply.Merge(dst, src)
}
func (m *GameInfoReply) XXX_Size() int {
	return xxx_messageInfo_GameInfoReply.Size(m)
}
func (m *GameInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_GameInfoReply proto.InternalMessageInfo

func (m *GameInfoReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type JaipurActionRequest struct {
	UserID               int32               `protobuf:"varint,1,opt,name=UserID,json=userID" json:"UserID,omitempty"`
	GameType             string              `protobuf:"bytes,2,opt,name=GameType,json=gameType" json:"GameType,omitempty"`
	GameID               int32               `protobuf:"varint,3,opt,name=GameID,json=gameID" json:"GameID,omitempty"`
	Action               *JaipurActionStruct `protobuf:"bytes,4,opt,name=Action,json=action" json:"Action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *JaipurActionRequest) Reset()         { *m = JaipurActionRequest{} }
func (m *JaipurActionRequest) String() string { return proto.CompactTextString(m) }
func (*JaipurActionRequest) ProtoMessage()    {}
func (*JaipurActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{8}
}
func (m *JaipurActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JaipurActionRequest.Unmarshal(m, b)
}
func (m *JaipurActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JaipurActionRequest.Marshal(b, m, deterministic)
}
func (dst *JaipurActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JaipurActionRequest.Merge(dst, src)
}
func (m *JaipurActionRequest) XXX_Size() int {
	return xxx_messageInfo_JaipurActionRequest.Size(m)
}
func (m *JaipurActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JaipurActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JaipurActionRequest proto.InternalMessageInfo

func (m *JaipurActionRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *JaipurActionRequest) GetGameType() string {
	if m != nil {
		return m.GameType
	}
	return ""
}

func (m *JaipurActionRequest) GetGameID() int32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *JaipurActionRequest) GetAction() *JaipurActionStruct {
	if m != nil {
		return m.Action
	}
	return nil
}

type JaipurActionReply struct {
	State                string   `protobuf:"bytes,1,opt,name=State,json=state" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JaipurActionReply) Reset()         { *m = JaipurActionReply{} }
func (m *JaipurActionReply) String() string { return proto.CompactTextString(m) }
func (*JaipurActionReply) ProtoMessage()    {}
func (*JaipurActionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{9}
}
func (m *JaipurActionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JaipurActionReply.Unmarshal(m, b)
}
func (m *JaipurActionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JaipurActionReply.Marshal(b, m, deterministic)
}
func (dst *JaipurActionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JaipurActionReply.Merge(dst, src)
}
func (m *JaipurActionReply) XXX_Size() int {
	return xxx_messageInfo_JaipurActionReply.Size(m)
}
func (m *JaipurActionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_JaipurActionReply.DiscardUnknown(m)
}

var xxx_messageInfo_JaipurActionReply proto.InternalMessageInfo

func (m *JaipurActionReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type JaipurActionStruct struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,json=type" json:"Type,omitempty"`
	Take                 int32    `protobuf:"varint,2,opt,name=Take,json=take" json:"Take,omitempty"`
	Sell                 []int32  `protobuf:"varint,3,rep,packed,name=Sell,json=sell" json:"Sell,omitempty"`
	SwitchSelfCard       []int32  `protobuf:"varint,4,rep,packed,name=SwitchSelfCard,json=switchSelfCard" json:"SwitchSelfCard,omitempty"`
	SwitchTargetCard     []int32  `protobuf:"varint,5,rep,packed,name=SwitchTargetCard,json=switchTargetCard" json:"SwitchTargetCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JaipurActionStruct) Reset()         { *m = JaipurActionStruct{} }
func (m *JaipurActionStruct) String() string { return proto.CompactTextString(m) }
func (*JaipurActionStruct) ProtoMessage()    {}
func (*JaipurActionStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamecenter_5d10a228dc12f194, []int{10}
}
func (m *JaipurActionStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JaipurActionStruct.Unmarshal(m, b)
}
func (m *JaipurActionStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JaipurActionStruct.Marshal(b, m, deterministic)
}
func (dst *JaipurActionStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JaipurActionStruct.Merge(dst, src)
}
func (m *JaipurActionStruct) XXX_Size() int {
	return xxx_messageInfo_JaipurActionStruct.Size(m)
}
func (m *JaipurActionStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_JaipurActionStruct.DiscardUnknown(m)
}

var xxx_messageInfo_JaipurActionStruct proto.InternalMessageInfo

func (m *JaipurActionStruct) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *JaipurActionStruct) GetTake() int32 {
	if m != nil {
		return m.Take
	}
	return 0
}

func (m *JaipurActionStruct) GetSell() []int32 {
	if m != nil {
		return m.Sell
	}
	return nil
}

func (m *JaipurActionStruct) GetSwitchSelfCard() []int32 {
	if m != nil {
		return m.SwitchSelfCard
	}
	return nil
}

func (m *JaipurActionStruct) GetSwitchTargetCard() []int32 {
	if m != nil {
		return m.SwitchTargetCard
	}
	return nil
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "api.TestRequest")
	proto.RegisterType((*TestReply)(nil), "api.TestReply")
	proto.RegisterType((*CreateGameRequest)(nil), "api.CreateGameRequest")
	proto.RegisterType((*Players)(nil), "api.Players")
	proto.RegisterType((*Player)(nil), "api.Player")
	proto.RegisterType((*CreateGameReply)(nil), "api.CreateGameReply")
	proto.RegisterType((*GameInfoRequest)(nil), "api.GameInfoRequest")
	proto.RegisterType((*GameInfoReply)(nil), "api.GameInfoReply")
	proto.RegisterType((*JaipurActionRequest)(nil), "api.JaipurActionRequest")
	proto.RegisterType((*JaipurActionReply)(nil), "api.JaipurActionReply")
	proto.RegisterType((*JaipurActionStruct)(nil), "api.JaipurActionStruct")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameCenterClient is the client API for GameCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameCenterClient interface {
	// Request & Res都要寫，不可空
	Ping(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error)
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameReply, error)
	GameInfo(ctx context.Context, in *GameInfoRequest, opts ...grpc.CallOption) (*GameInfoReply, error)
	JaipurAction(ctx context.Context, in *JaipurActionRequest, opts ...grpc.CallOption) (*JaipurActionReply, error)
}

type gameCenterClient struct {
	cc *grpc.ClientConn
}

func NewGameCenterClient(cc *grpc.ClientConn) GameCenterClient {
	return &gameCenterClient{cc}
}

func (c *gameCenterClient) Ping(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error) {
	out := new(TestReply)
	err := c.cc.Invoke(ctx, "/api.GameCenter/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameReply, error) {
	out := new(CreateGameReply)
	err := c.cc.Invoke(ctx, "/api.GameCenter/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterClient) GameInfo(ctx context.Context, in *GameInfoRequest, opts ...grpc.CallOption) (*GameInfoReply, error) {
	out := new(GameInfoReply)
	err := c.cc.Invoke(ctx, "/api.GameCenter/GameInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterClient) JaipurAction(ctx context.Context, in *JaipurActionRequest, opts ...grpc.CallOption) (*JaipurActionReply, error) {
	out := new(JaipurActionReply)
	err := c.cc.Invoke(ctx, "/api.GameCenter/JaipurAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameCenterServer is the server API for GameCenter service.
type GameCenterServer interface {
	// Request & Res都要寫，不可空
	Ping(context.Context, *TestRequest) (*TestReply, error)
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameReply, error)
	GameInfo(context.Context, *GameInfoRequest) (*GameInfoReply, error)
	JaipurAction(context.Context, *JaipurActionRequest) (*JaipurActionReply, error)
}

func RegisterGameCenterServer(s *grpc.Server, srv GameCenterServer) {
	s.RegisterService(&_GameCenter_serviceDesc, srv)
}

func _GameCenter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCenterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameCenter/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCenterServer).Ping(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameCenter_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCenterServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameCenter/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCenterServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameCenter_GameInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCenterServer).GameInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameCenter/GameInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCenterServer).GameInfo(ctx, req.(*GameInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameCenter_JaipurAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JaipurActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCenterServer).JaipurAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameCenter/JaipurAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCenterServer).JaipurAction(ctx, req.(*JaipurActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GameCenter",
	HandlerType: (*GameCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GameCenter_Ping_Handler,
		},
		{
			MethodName: "CreateGame",
			Handler:    _GameCenter_CreateGame_Handler,
		},
		{
			MethodName: "GameInfo",
			Handler:    _GameCenter_GameInfo_Handler,
		},
		{
			MethodName: "JaipurAction",
			Handler:    _GameCenter_JaipurAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gamecenter.proto",
}

func init() { proto.RegisterFile("gamecenter.proto", fileDescriptor_gamecenter_5d10a228dc12f194) }

var fileDescriptor_gamecenter_5d10a228dc12f194 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0x1c, 0x3b, 0x6e, 0x33, 0x69, 0xd3, 0x74, 0xbe, 0x2a, 0x58, 0xb9, 0x0a, 0x96, 0x28,
	0xa1, 0x48, 0x41, 0x0a, 0x52, 0xaf, 0xb8, 0x80, 0x26, 0x12, 0x04, 0x55, 0xa8, 0xb2, 0x13, 0x71,
	0xc5, 0xc5, 0x12, 0xa6, 0xc6, 0xaa, 0x63, 0x1b, 0x7b, 0x2d, 0x94, 0xd7, 0xe0, 0x11, 0x10, 0x4f,
	0xc8, 0x13, 0x20, 0xcf, 0x3a, 0xed, 0x26, 0xa9, 0xef, 0x7c, 0xce, 0xfc, 0xec, 0xd9, 0x33, 0xb3,
	0x86, 0x6e, 0x20, 0x56, 0xb4, 0xa4, 0x58, 0x52, 0x36, 0x4a, 0xb3, 0x44, 0x26, 0x68, 0x8a, 0x34,
	0x74, 0x8f, 0xa1, 0x3d, 0xa7, 0x5c, 0x7a, 0xf4, 0xa3, 0xa0, 0x5c, 0xba, 0x4f, 0xa1, 0xa5, 0x60,
	0x1a, 0xad, 0xf1, 0x0c, 0x9a, 0xbe, 0x14, 0x92, 0x1c, 0x63, 0x60, 0x0c, 0x5b, 0x5e, 0x33, 0x2f,
	0x81, 0x9b, 0xc0, 0xe9, 0x24, 0x23, 0x21, 0xe9, 0xbd, 0x58, 0x51, 0x55, 0x87, 0x7d, 0x38, 0x2c,
	0xe1, 0x7c, 0x9d, 0x6e, 0xb2, 0x0f, 0x83, 0x0a, 0x63, 0x0f, 0xec, 0x32, 0x36, 0x9b, 0x3a, 0x8d,
	0x81, 0x31, 0x6c, 0x7a, 0x76, 0xc0, 0x08, 0xcf, 0xe1, 0xe0, 0x26, 0x12, 0x6b, 0xca, 0x72, 0xc7,
	0x1c, 0x18, 0xc3, 0xf6, 0xf8, 0x68, 0x24, 0xd2, 0x70, 0x54, 0x71, 0xde, 0x41, 0xaa, 0x3e, 0xdc,
	0xcb, 0xfb, 0x3c, 0x7c, 0x09, 0xa0, 0x3e, 0xaf, 0xc3, 0x5c, 0x3a, 0xc6, 0xc0, 0x1c, 0xb6, 0xc7,
	0x6d, 0xad, 0xca, 0x83, 0xf4, 0x3e, 0xec, 0xbe, 0x05, 0x5b, 0xb1, 0xd8, 0x81, 0xc6, 0x6c, 0xca,
	0xba, 0x9a, 0x5e, 0x23, 0x9c, 0x22, 0x82, 0xb5, 0x58, 0x54, 0x7a, 0x5a, 0x9e, 0x55, 0x2c, 0x66,
	0xcc, 0x7d, 0x12, 0x2b, 0x62, 0x29, 0x2d, 0xcf, 0x8a, 0xc5, 0x8a, 0xdc, 0xe7, 0x70, 0xa2, 0x5f,
	0xb5, 0xde, 0x93, 0x2f, 0x70, 0xc2, 0x57, 0x8c, 0x6f, 0x93, 0x8d, 0x23, 0x3d, 0xb0, 0x17, 0x39,
	0x65, 0x7c, 0xae, 0x59, 0xde, 0xba, 0x60, 0x54, 0xeb, 0x86, 0xee, 0xa0, 0xb9, 0xed, 0xa0, 0xfb,
	0x0c, 0x8e, 0x1f, 0xda, 0xd7, 0xab, 0xf8, 0x65, 0xc0, 0xff, 0x1f, 0x45, 0x98, 0x16, 0xd9, 0xbb,
	0xa5, 0x0c, 0x93, 0xf8, 0x31, 0x29, 0x86, 0x26, 0x45, 0x3f, 0xb2, 0x51, 0x3b, 0x34, 0x73, 0x4b,
	0xe6, 0x2b, 0xb0, 0x55, 0x73, 0xc7, 0xe2, 0x99, 0x3d, 0x61, 0xf7, 0xf5, 0x53, 0x7d, 0x99, 0x15,
	0x4b, 0xe9, 0xd9, 0x82, 0x91, 0xfb, 0x02, 0x4e, 0xb7, 0x35, 0xd5, 0xeb, 0xff, 0x63, 0x00, 0xee,
	0x77, 0x2a, 0x27, 0xa3, 0xed, 0x95, 0x25, 0x4b, 0x79, 0x25, 0x27, 0xee, 0xa8, 0xf2, 0xd0, 0x92,
	0xe2, 0x8e, 0x39, 0x9f, 0xa2, 0xc8, 0x31, 0xd9, 0x6f, 0x2b, 0xa7, 0x28, 0xc2, 0x73, 0xe8, 0xf8,
	0x3f, 0x43, 0xb9, 0xfc, 0xee, 0x53, 0x74, 0x3b, 0x11, 0xd9, 0x37, 0xc7, 0xe2, 0x68, 0x27, 0xdf,
	0x62, 0xf1, 0x02, 0xba, 0x2a, 0x6f, 0x2e, 0xb2, 0x80, 0x24, 0x67, 0x36, 0x39, 0xb3, 0x9b, 0xef,
	0xf0, 0xe3, 0xbf, 0x06, 0x40, 0xe9, 0xcd, 0x84, 0x1f, 0x13, 0x5e, 0x80, 0x75, 0x13, 0xc6, 0x01,
	0x76, 0xd9, 0x09, 0xed, 0x31, 0xf5, 0x3b, 0x1a, 0x93, 0x46, 0x6b, 0xf7, 0x3f, 0x7c, 0x03, 0xf0,
	0xb0, 0x50, 0xd8, 0xe3, 0xf8, 0xde, 0x63, 0xea, 0x9f, 0xed, 0xf1, 0xaa, 0xfa, 0x52, 0xcd, 0xab,
	0x5c, 0x03, 0x54, 0x39, 0x3b, 0x4b, 0xd7, 0xc7, 0x1d, 0x56, 0xd5, 0x5d, 0xc1, 0x91, 0x6e, 0x2b,
	0x3a, 0x7b, 0x33, 0xdb, 0xd4, 0xf7, 0x1e, 0x89, 0x70, 0x8f, 0x2b, 0xfb, 0x77, 0xc3, 0xfc, 0x70,
	0xfd, 0xf9, 0xab, 0xcd, 0xff, 0x8e, 0xd7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xbd, 0x75,
	0x67, 0x4f, 0x04, 0x00, 0x00,
}
